# -*- coding: utf-8 -*-
"""AddRegionsColumn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qbbSP-vJFuEqxJzd3hGVTNei4LEV3wLj
"""

from google.colab import files
uploaded = files.upload()

pip install reverse_geocoder

pip install pprint

import reverse_geocoder as rg 
import pprint 
import csv
import json
from collections import OrderedDict
import pandas as pd
import numpy as np



df = pd.read_csv('3DMassing_2018_WGS84.csv')
df = df.set_index('Unnamed: 0')
df['burrow'] = np.zeros(len(df.index))  


lst = []
for i,j in enumerate(df.LONGITUDE):
  long = j
  lat = df.LATITUDE[i]
  coordinates = (long,lat)
  lst.append(dict(rg.search(coordinates)[0])['name'])
  
df['burrow'] = lst
  

print(df)
  
df.to_csv('trolol.csv')
#coordinates =(43.66030373, -79.59226603) 
#result = rg.search(coordinates)  
#print(dict(result[0])['name'])



#pprint.pprint(json.dumps(result)) 




#print(df)